---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "· Homelab Services"
subtitle: "Dima Denisenko's"
logo: "https://avatars.githubusercontent.com/u/91197884?s=200&v=4"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>This project is intended to demonstrate end-to-end best practices for building a cloud native, event driven microservice architecture using Spring Boot.</p>' # set false if you want to hide it.

defaults:
  layout: list
  colorTheme: dark

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#054fa3"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#012759"
    highlight-secondary: "#003273"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  url: https://microservices.io/
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "RESTful APIs, distributed services, cloud-native architecture."
  icon: "fa fa-grin"
  content: "<h3>Tech Stack</h3><p><img src='https://img.shields.io/badge/springboot-%236DB33F.svg?style=for-the-badge&logo=springboot&logoColor=white'> <img src='https://img.shields.io/badge/java-%23ED8B00.svg?style=for-the-badge&logo=java&logoColor=white'> <img src='https://img.shields.io/badge/kubernetes-326CE5.svg?style=for-the-badge&logo=kubernetes&logoColor=white'>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "KnowHowSpringBoot Bootcamp"
    icon: "fab fa-github"
    url: "https://github.com/KnowHowSpringBoot"
    target: "_blank" # optional html a tag target attribute
  - name: "Repositories"
    icon: "fas fa-book"
    url: "https://github.com/orgs/KnowHowSpringBoot/repositories"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Server Management"
    icon: "fas fa-server"
    items:
      - name: "Proxmox Admin"
        logo: "https://camo.githubusercontent.com/2df2ac41e1b8a1484be236c75e395981b31bfd670eff46b5c182ea0be9475310/68747470733a2f2f7777772e70726f786d6f782e636f6d2f696d616765732f70726f786d6f782f50726f786d6f785f73796d626f6c5f7374616e646172645f6865782e706e67"
        subtitle: "manage VMs"
        tag: "cluster"
        keywords: ""
        url: "https://pve.c2a2.com/"
        target: "_blank" # optional html a tag target attribute

      - name: "Nginx Proxy Manager"
        logo: "https://nginxproxymanager.com/icon.png"
        subtitle: "reverse proxy"
        tag: "hosts"
        keywords: "manage virtual hosts"
        url: "https://hosts.c2a2.com/"
        target: "_blank"
  - name: "K8s Cluster"
    icon: "fas fa-dharmachakra"
    items:
      - name: "Kubernetes Dashboard"
        logo: "https://github.com/kubernetes/community/blob/master/icons/png/infrastructure_components/unlabeled/control-plane-128.png?raw=true"
        subtitle: "manage workloads"
        tag: "orchestration"
        keywords: ""
        url: "https://dashboard.gee8.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "Grafana"
        logo: "https://cdn.iconscout.com/icon/free/png-512/free-grafana-3521466-2944910.png?f=avif&w=256"
        subtitle: "monitoring"
        tag: "observability"
        keywords: ""
        url: "https://gee8.com/grafana/"
        target: "_blank"
      - name: "Prometheus"
        logo: "https://cdn.iconscout.com/icon/free/png-512/free-grafana-3521466-2944910.png?f=avif&w=256"
        subtitle: "monitoring"
        tag: "observability"
        keywords: ""
        url: "https://gee8.com/prometheus/"
        target: "_blank"
      - name: "Jaeger UI"
        logo: "https://www.jaegertracing.io/img/jaeger-icon-reverse-color.svg"
        subtitle: "traces"
        tag: "observability"
        keywords: "observability"
        url: "https://gee8.com/jaeger/search"
      - name: "AlertManager"
        logo: "https://luktom.net/wordpress/wp-content/uploads/2019/05/prometheus.png"
        subtitle: "alerts"
        tag: "observability"
        keywords: ""
        url: "https://gee8.com/alertmanager/"

  - name: "CI / CD"
    icon: "fas fa-robot"
    items:
      - name: "Code"
        logo: "https://img.icons8.com/?size=512&id=52539&format=png"
        subtitle: "KnowHowSpringBoot Bootcamp"
        tag: "github"
        keywords: "pipelines"
        url: "https://github.com/KnowHowSpringBoot"
        target: "_blank"

      - name: "Drone CI"
        logo: "https://img.icons8.com/?size=512&id=DtBUUQ8v7hOR&format=png"
        subtitle: "Automation Server"
        tag: "job runner"
        keywords: "pipelines"
        url: "https://know-how.run/"
        target: "_blank"

      - name: "SonarQube"
        logo: "https://seeklogo.com/images/S/sonarqube-logo-AF25541AAF-seeklogo.com.png"
        subtitle: "continuous inspection of code quality"
        tag: "quality gateway"
        keywords: ""
        url: "https://know-how.report/"
        target: "_blank"

      - name: "Nexus"
        logo: "https://assets-global.website-files.com/5f10ed4c0ebf7221fb5661a5/5f2af61146c55b6e172fa5b3_NexusRepo_Icon.png"
        subtitle: "Repository Management"
        tag: "artifacts"
        keywords: ""
        url: "https://know-how.nexus/"
        target: "_blank"

      - name: "Containers"
        logo: "https://img.icons8.com/?size=512&id=22813&format=png"
        subtitle: "Images distribution"
        tag: "containerization"
        keywords: ""
        url: "https://know-how.download/"
        target: "_blank"

      - name: "Containers (svc)"
        logo: "https://img.icons8.com/?size=512&id=22813&format=png"
        subtitle: "Images distribution"
        tag: "containerization"
        keywords: ""
        url: "https://know-how.sbs/"
        target: "_blank"

